name: Scheduled Versioning

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 15 8 *'

jobs:
  versioning:
    name: Versioning System
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: validator
        run: |
          pip3 install -r requirements.txt

      - name: Execute versioning script
        env:
          JIRA_API_KEY: ${{ secrets.JIRA_API_KEY }}
        working-directory: ./validator/scripts
        run: python diff.py
